### Problem 1:
Write a function so that the columns of the output matrix are powers of the input vector. <br>
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. <br>
<strong>HINT</strong>: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

def ATV_matrix(in_vec, n, increasing=True):
    out_vec = np.empty(shape=(len(in_vec), n))
    
    in_vec = np.array(in_vec)
    
    if increasing:
        pows = [i for i in range(n)]
    else:
        pows = [i for i in range(n-1,-1, -1)]
        
    for i in range(len(pows)):
        for j in range(len(in_vec)):
            out_vec[j][i] = in_vec[j]**pows[i]
    return out_vec

In [2]:
print(ATV_matrix(in_vec=[1, 2, 3, 4], n=5))

[[  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]


In [3]:
print(ATV_matrix(in_vec=[1, 2, 3, 4], n=5, increasing=False))

[[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]]


### Problem 2:
Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def moving_avg(in_vec, k=1):
    out_vec = np.empty(shape=(len(in_vec)-k+1, 1))
    if k < 1:
        return 'Error: k should be greater than 1.'
    
    elif len(in_vec) < k:
        return 'Error: length of input vector should be greater than or equal to k.'
    
    else:
        for i in range(len(in_vec)-k+1):
            sum_win = 0
            for j in range(k):
                sum_win += in_vec[i+j]
            out_vec[i] = (sum_win/k)
    return out_vec

In [5]:
print(moving_avg(in_vec=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100], k=4))

[[25.]
 [35.]
 [45.]
 [55.]
 [65.]
 [75.]
 [85.]]


In [6]:
print(moving_avg(in_vec=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], k=3))

[[  5.        ]
 [  4.66666667]
 [  5.66666667]
 [  6.66666667]
 [  9.66666667]
 [ 28.66666667]
 [ 49.33333333]
 [ 72.66666667]
 [ 84.        ]
 [ 93.33333333]
 [116.33333333]]
